version: '3'

services:

  frontend:
    build: ./frontend
    container_name: glitch_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./frontend/app:/app
      - /app/glitch/node_modules
    tty: true
    stdin_open: true
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: glitch_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    tty: true
    stdin_open: true

  nginx:
    build: ./nginx
    container_name: glitch_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    environment:
      - FRONTEND_PATH=${FRONTEND_PATH}
      - DISABLE_CACHE=${DISABLE_CACHE}
