version: '3'

services:

  frontend:
    build:
      context: ./frontend
      args:
        MODE: ${MODE:-development}
    container_name: glitch_frontend
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - NODE_ENV=${MODE:-development}
    volumes:
      - ./frontend/app:/app
      - /app/glitch/node_modules
    tty: true
    stdin_open: true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        MODE: ${MODE:-development}
    container_name: glitch_backend
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - MODE=${MODE:-development}
    volumes:
      - ./backend/app:/app
    tty: true
    stdin_open: true

  nginx:
    build:
      context: ./nginx
      args:
        MODE: ${MODE:-development}
    container_name: glitch_nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - frontend
      - backend
    environment:
      - FRONTEND_HOST=frontend
      - BACKEND_HOST=backend
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - MODE=${MODE:-development}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/entrypoint.sh:/entrypoint.sh
    tty: true
    stdin_open: true
