version: '3.8'

services:
  backend:
    build: ./backend
    container_name: glitch_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    tty: true
    stdin_open: true
    networks:
      - webnet

networks:
  webnet:
